
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_WEBAPI.Context
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    public string Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public Nullable<bool> EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<bool> PhoneNumberConfirmed { get; set; }

    public Nullable<bool> TwoFactorEnabled { get; set; }

    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }

    public Nullable<bool> LockoutEnabled { get; set; }

    public Nullable<int> AccessFailedCount { get; set; }

    public string UserName { get; set; }

    public string MA_DVIQLY { get; set; }

    public Nullable<int> MA_PBAN { get; set; }

    public string ChucDanh { get; set; }

    public string AnhDaiDien { get; set; }



    public virtual tbl_Company tbl_Company { get; set; }

}

}
