//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcbs_LichSu
    {
        public int Id { get; set; }
        public Nullable<int> NoiDungId { get; set; }
        public string NoiDung { get; set; }
        public string PhamVi { get; set; }
        public string KhoiLuongVTTB { get; set; }
        public decimal TongGiaTri { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public string LyDo { get; set; }
    }
}
