//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatTinNhan
    {
        public long MaTN { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string NoiDung { get; set; }
        public string MaGui { get; set; }
        public string MaNhan { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<byte> MaTT { get; set; }
        public Nullable<long> MaCha { get; set; }
    }
}
