//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemSoatDienThoai
    {
        public int Id { get; set; }
        public string Hoten { get; set; }
        public string Chucvu { get; set; }
        public string TenDonVi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> BaoCaoCuoiNgayId { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual tblBaoCaoCuoiNgay tblBaoCaoCuoiNgay { get; set; }
    }
}
