//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int MenuId { get; set; }
        public Nullable<int> MenuParentId { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string MenuCode { get; set; }
        public string MenuText { get; set; }
        public string MenuOrder { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsNewLetter { get; set; }
        public Nullable<bool> IsShowMenu { get; set; }
        public Nullable<bool> IsFrontPage { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public string RoleId { get; set; }
        public string Class { get; set; }
        public Nullable<int> RoleView { get; set; }
    }
}
