//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<int> LoaiThongBao { get; set; }
        public string MaTaiKhoan { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MA_DVIQLY { get; set; }
        public string MA_PBAN { get; set; }
        public Nullable<long> PhienLamViecId { get; set; }
    }
}
