//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuLamViec_Images
    {
        public int ID { get; set; }
        public Nullable<int> MaHA { get; set; }
        public Nullable<int> MaPCT { get; set; }
    
        public virtual plv_PhieuCongTac plv_PhieuCongTac { get; set; }
        public virtual tblImage tblImage { get; set; }
    }
}
