//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class plv_PhieuCT_NhanVien
    {
        public int MaPCT { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> ThoiGianDen { get; set; }
        public Nullable<System.DateTime> ThoiGianRut { get; set; }
        public Nullable<bool> IsDen { get; set; }
        public Nullable<bool> IsRut { get; set; }
    
        public virtual plv_PhieuCongTac plv_PhieuCongTac { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
