//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class plv_PhieuCongTac_His
    {
        public int ID { get; set; }
        public string SoPhieu { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaLP { get; set; }
        public Nullable<int> MaTT { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
        public string NguoiCN { get; set; }
        public Nullable<int> NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
    }
}
