//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class plv_PhieuCongTac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plv_PhieuCongTac()
        {
            this.PhieuLamViec_Images = new HashSet<PhieuLamViec_Images>();
            this.plv_PhieuCT_NhanVien = new HashSet<plv_PhieuCT_NhanVien>();
            this.plv_TaiLieu = new HashSet<plv_TaiLieu>();
        }
    
        public int ID { get; set; }
        public string SoPhieu { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaLP { get; set; }
        public Nullable<int> MaTT { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
        public string NguoiCN { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string DieuKienAnToan { get; set; }
        public string DonViLienQuanQLVH { get; set; }
        public string NguoiChoPhep { get; set; }
        public string GiayBanGiaoQLVH { get; set; }
        public string ChiTietCatDien { get; set; }
        public string ChiTietNoiDat { get; set; }
        public string ChiTietRaoChan { get; set; }
        public string ChiTietBienBao { get; set; }
        public string PhamViLamViec { get; set; }
        public string CanhBaoNguyHiem { get; set; }
        public Nullable<bool> CHTT_B2 { get; set; }
        public Nullable<bool> GSAT_B2 { get; set; }
        public Nullable<System.DateTime> NgayGioKT_B2 { get; set; }
        public Nullable<bool> NGUOICP_B2 { get; set; }
        public string NoiDatTai { get; set; }
        public string AnToanKhac { get; set; }
        public Nullable<bool> CHTT_B3 { get; set; }
        public Nullable<bool> GSAT_B3 { get; set; }
        public Nullable<System.DateTime> NgayGioKT_B3 { get; set; }
        public Nullable<bool> CHTT_B6 { get; set; }
        public Nullable<bool> NGUOICP_B6 { get; set; }
        public Nullable<System.DateTime> NgayGioKT_B6 { get; set; }
        public Nullable<bool> NguoiTaoKT_B6 { get; set; }
        public Nullable<int> TrangThaiChuyen { get; set; }
        public string DonViId { get; set; }
        public Nullable<int> SoNguoiThamGia { get; set; }
        public string NguoiCapPhieu { get; set; }
        public string NguoiCapPhieu_Id { get; set; }
        public Nullable<int> SoPhieuLenhInt { get; set; }
        public Nullable<bool> IsChuyenNPC { get; set; }
        public Nullable<System.DateTime> NgayDuyetNPC { get; set; }
        public string NguoiDuyetNPC { get; set; }
        public string TenDonVi_LCT { get; set; }
        public Nullable<int> PhongBanID_PCT { get; set; }
        public string PhongBan_PCT { get; set; }
        public Nullable<int> LoaiCongViecId { get; set; }
        public string MaYeuCauCRM { get; set; }
        public Nullable<int> TramId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuLamViec_Images> PhieuLamViec_Images { get; set; }
        public virtual plv_LoaiPhieu plv_LoaiPhieu { get; set; }
        public virtual plv_TrangThaiPhieu plv_TrangThaiPhieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plv_PhieuCT_NhanVien> plv_PhieuCT_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plv_TaiLieu> plv_TaiLieu { get; set; }
    }
}
