//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_ChiTieuSuCoTHASauMT
    {
        public int Id { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public string DonViId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<int> ChiTieuNam { get; set; }
        public Nullable<int> ChiTieuThang { get; set; }
        public Nullable<bool> NPCIsOpen { get; set; }
        public string NPCNguoiMo { get; set; }
        public Nullable<System.DateTime> NPCNgayMo { get; set; }
        public string NPCNguoiTao { get; set; }
        public Nullable<System.DateTime> NPCNgayTao { get; set; }
        public string NPCNguoiSua { get; set; }
        public Nullable<System.DateTime> NPCNgaySua { get; set; }
        public Nullable<int> SoVuSauMT { get; set; }
        public Nullable<int> ChiTieuThangSauDieuChuyen { get; set; }
        public Nullable<int> SoVuTruocMT { get; set; }
    }
}
