//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_PhanTuDien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sc_PhanTuDien()
        {
            this.sc_SuCoPTD = new HashSet<sc_SuCoPTD>();
        }
    
        public int Id { get; set; }
        public string DinhDanh { get; set; }
        public string TenPhanTu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> LoaiPhanTuId { get; set; }
    
        public virtual sc_LoaiPhanTu sc_LoaiPhanTu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_SuCoPTD> sc_SuCoPTD { get; set; }
    }
}
