//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBaoCaoCuoiNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBaoCaoCuoiNgay()
        {
            this.KiemSoatDienThoais = new HashSet<KiemSoatDienThoai>();
            this.tblChiTietBaoCaoCuoiNgays = new HashSet<tblChiTietBaoCaoCuoiNgay>();
        }
    
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string DonViId { get; set; }
        public string TruongDonVi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public Nullable<int> So_CV_KH { get; set; }
        public Nullable<int> So_CV_BS { get; set; }
        public Nullable<int> So_CV_Ko_KH { get; set; }
        public Nullable<int> Tong_PTT { get; set; }
        public Nullable<int> Tong_PCT { get; set; }
        public Nullable<int> Tong_LCT { get; set; }
        public Nullable<int> So_Dvi_GuiAnh { get; set; }
        public Nullable<int> So_Dvi_Ktra { get; set; }
        public string ChiTietDviKtra { get; set; }
        public Nullable<int> Kq_SoBB { get; set; }
        public Nullable<int> Kq_KiemTra { get; set; }
        public Nullable<int> Kq_Cv_KoDat { get; set; }
        public Nullable<int> Kq_Cv_KetThuc { get; set; }
        public string ViPham { get; set; }
        public string DeNghi { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<int> So_CV_DX { get; set; }
        public Nullable<int> So_Dvi_ChuaGuiAnh { get; set; }
        public Nullable<int> Tong_So_PhienLV { get; set; }
        public Nullable<int> So_Dvi_GuiThemAnh { get; set; }
        public Nullable<int> Tong_So_PhienLV_ChuaGuiAnh_NgayHomTruoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiemSoatDienThoai> KiemSoatDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBaoCaoCuoiNgay> tblChiTietBaoCaoCuoiNgays { get; set; }
    }
}
