//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBaoCao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBaoCao()
        {
            this.tblBienBanKiemTras = new HashSet<tblBienBanKiemTra>();
            this.tblChiTietBaoCaos = new HashSet<tblChiTietBaoCao>();
        }
    
        public int Id { get; set; }
        public string DonViId { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public short So_BPTC_ATLD { get; set; }
        public short So_PTT { get; set; }
        public short So_PCT { get; set; }
        public short Lenh_CT { get; set; }
        public short So_P_ATLD { get; set; }
        public short So_BB_ATLD { get; set; }
        public short So_BPTC_ATLD_TT { get; set; }
        public short So_PTT_TT { get; set; }
        public short So_PCT_TT { get; set; }
        public short Lenh_CT_TT { get; set; }
        public short So_CV_DB { get; set; }
        public string ChiTiet_CV_DB { get; set; }
        public short So_CV_DK { get; set; }
        public string ChiTiet_CV_DK { get; set; }
        public short So_CV_BS { get; set; }
        public string ChiTiet_CV_BS { get; set; }
        public short So_CV_HB { get; set; }
        public string NoiDung_CV_HB { get; set; }
        public string LyDo_CV_HB { get; set; }
        public short SoNguoiViPham { get; set; }
        public string ChiTietViPham { get; set; }
        public string So_BPTC_ATLD_TT_CT { get; set; }
        public string So_PTT_TT_CT { get; set; }
        public string So_PCT_TT_CT { get; set; }
        public string Lenh_CT_TT_CT { get; set; }
        public Nullable<short> So_CV_DK_PCT { get; set; }
        public Nullable<short> So_CV_DK_LC { get; set; }
        public Nullable<short> So_CV_XH { get; set; }
        public string LyDo_CV_XH { get; set; }
        public Nullable<short> TongSoCV { get; set; }
        public Nullable<int> LoaiBaoCao { get; set; }
        public short So_CV_DX { get; set; }
        public string ChiTiet_CV_DX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBienBanKiemTra> tblBienBanKiemTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBaoCao> tblChiTietBaoCaos { get; set; }
    }
}
