//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBienBanKiemTra
    {
        public int Id { get; set; }
        public string DonViId { get; set; }
        public int PhongBanId { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public string DiaDiem { get; set; }
        public string NguoiChuTri { get; set; }
        public string ChucVuNguoiChuTri { get; set; }
        public short So_Nguoi_TD { get; set; }
        public string TrangBiCaNhan { get; set; }
        public string TrangBiThiCong { get; set; }
        public string TrangBiAnToan { get; set; }
        public string TrangBiKhac { get; set; }
        public string YKien_NhacNho { get; set; }
        public string TepDinhKem { get; set; }
        public Nullable<int> BaoCaoId { get; set; }
    
        public virtual tblBaoCao tblBaoCao { get; set; }
    }
}
