//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietBaoCao
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public string UrlFile { get; set; }
        public Nullable<int> IdBaoCao { get; set; }
    
        public virtual tblBaoCao tblBaoCao { get; set; }
    }
}
