//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int Id { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Username { get; set; }
        public short Priority { get; set; }
        public string Description { get; set; }
        public Nullable<int> PhienLamViecId { get; set; }
    
        public virtual tblPhienLamViec tblPhienLamViec { get; set; }
    }
}
