//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDonVi()
        {
            this.tblPhongBans = new HashSet<tblPhongBan>();
        }
    
        public string Id { get; set; }
        public string TenDonVi { get; set; }
        public string TenVietTat { get; set; }
        public string MoTa { get; set; }
        public string DviCha { get; set; }
        public Nullable<int> CapDvi { get; set; }
        public Nullable<int> ViTri { get; set; }
        public string SDT { get; set; }
        public Nullable<int> MaLP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhongBan> tblPhongBans { get; set; }
    }
}
