//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevice
    {
        public int ID { get; set; }
        public string TOKENKEY { get; set; }
        public string MACHINE_TYPE { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
    }
}
