//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage_His
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Note { get; set; }
        public string Comment { get; set; }
        public string Tag { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> PhienLamViecId { get; set; }
        public string UserUp { get; set; }
        public Nullable<int> isVideo { get; set; }
        public string VideoPath { get; set; }
        public Nullable<decimal> KinhDo { get; set; }
        public Nullable<decimal> ViDo { get; set; }
        public Nullable<System.DateTime> NgayChup { get; set; }
        public Nullable<double> ImgSize { get; set; }
        public string Type { get; set; }
        public string UrlThumb { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    }
}
