//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.plv_PhieuCT_NhanVien = new HashSet<plv_PhieuCT_NhanVien>();
            this.tblPhienLamViec_TheoDoi = new HashSet<tblPhienLamViec_TheoDoi>();
        }
    
        public string Id { get; set; }
        public string TenNhanVien { get; set; }
        public string ChucVu { get; set; }
        public string UrlImage { get; set; }
        public string BacHT { get; set; }
        public string BacThi { get; set; }
        public string BacAnToan { get; set; }
        public string Username { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDT { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsCapPhieu { get; set; }
        public Nullable<bool> IsLanhDaoCv { get; set; }
        public Nullable<bool> IschiHuyTT { get; set; }
        public Nullable<bool> IsNguoiChoPhep { get; set; }
        public Nullable<bool> IsGiamSatAT { get; set; }
        public Nullable<bool> IsNguoiRaLenh { get; set; }
        public Nullable<bool> IsThiHanhLenh { get; set; }
        public Nullable<int> PhongBanId { get; set; }
        public string DonViId { get; set; }
        public Nullable<System.Guid> ConnectionId { get; set; }
        public Nullable<System.DateTime> NgayDangNhap { get; set; }
        public byte[] ChuKySo { get; set; }
        public string NhaMangSDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plv_PhieuCT_NhanVien> plv_PhieuCT_NhanVien { get; set; }
        public virtual tblPhongBan tblPhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhienLamViec_TheoDoi> tblPhienLamViec_TheoDoi { get; set; }
    }
}
