//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhienLamViec_TheoDoi
    {
        public int PhienLamViecId { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string DonViId { get; set; }
        public Nullable<int> PhongBanId { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblPhienLamViec tblPhienLamViec { get; set; }
    }
}
