//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_WEBAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbnn_ThietBiNghiemNgat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbnn_ThietBiNghiemNgat()
        {
            this.tbnn_SoTheoDoiTBNN = new HashSet<tbnn_SoTheoDoiTBNN>();
        }
    
        public int ID { get; set; }
        public string TenThietBi { get; set; }
        public string MaHieu { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<System.DateTime> NgayDuaVaoSuDung { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public string DonViQuanLyId { get; set; }
        public string DonViId { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> HanKiemDinh { get; set; }
        public string SoCheTao { get; set; }
        public string SoDangKy { get; set; }
        public Nullable<decimal> TaiTrongThietKe { get; set; }
        public Nullable<decimal> TaiTrongChoPhep { get; set; }
        public string HoSoThietBi { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string QuyTacDanhMa { get; set; }
        public Nullable<int> MaTT { get; set; }
        public string HangSanXuat { get; set; }
        public string NuocSanXuat { get; set; }
    
        public virtual tblPhongBan tblPhongBan { get; set; }
        public virtual tbnn_LoaiThietBi tbnn_LoaiThietBi { get; set; }
        public virtual tbnn_NhomThietBi tbnn_NhomThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbnn_SoTheoDoiTBNN> tbnn_SoTheoDoiTBNN { get; set; }
        public virtual tbnn_TrangThai tbnn_TrangThai { get; set; }
    }
}
